package com.github.jvsena42.loopky.cli

import com.github.jvsena42.loopky.data.nexus.HttpFetcher
import com.github.jvsena42.loopky.data.nexus.HttpRequest
import com.github.jvsena42.loopky.data.nexus.JvmHttpFetcher
import com.github.jvsena42.loopky.data.storage.ConfigHome
import com.github.jvsena42.loopky.util.Log
import com.github.jvsena42.loopky.util.runSuspendCatching
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption

/**
 * What the newest published release says about itself (#209).
 *
 * A tiny JSON file attached to the release, generated by the release workflow **from the binary it
 * just built** rather than from a source constant — so it cannot claim a version or a schema the
 * artifact beside it does not answer with.
 */
@Serializable
data class ReleaseManifest(val version: String, val schema: Int)

/** A release newer than this binary. Null everywhere else, including "the check did not run". */
data class UpdateAvailable(
    val version: String,
    val schema: Int,
    /**
     * The released `--json` schema differs from this binary's.
     *
     * Reported apart from the version because it is a different severity. A newer CLI at the same
     * schema is a convenience; a newer CLI at a *different* schema means the consumer's parser may
     * be reading fields whose meaning it has assumed rather than checked, which is the one thing
     * versioning the envelope from the first release was for.
     */
    val schemaChanged: Boolean,
)

/**
 * Asks, once a day, whether a newer `loopky` exists — and never lets the answer matter.
 *
 * Three properties, all of them constraints rather than preferences:
 *
 * - **It never fails the command.** No egress, an allowlist proxy, a rate-limited endpoint and a
 *   release with no manifest yet are all ordinary in the environments this runs in, and none of
 *   them is a reason a `deck create` should not happen. Every path here returns null.
 * - **It never checks twice in a day.** The answer is cached beside the session, and a *failed*
 *   check is cached too — otherwise a box with no egress pays a DNS timeout on every invocation,
 *   which is precisely the cost an agent doing 200 writes notices.
 * - **It points at the host the install already uses.** `releases/latest/download/…` is where
 *   `cli/install.sh` fetches the binary from, so an allowlist that permits installing `loopky`
 *   permits checking for it, and the check adds no host to anybody's proxy configuration. The
 *   GitHub REST API would have been one host too, and a rate-limited one; this is a redirect to
 *   the same object store the binary itself comes from.
 */
class UpdateChecker(
    private val configHome: Path,
    private val repo: String = DEFAULT_REPO,
    private val fetcher: HttpFetcher = JvmHttpFetcher(),
    private val now: () -> Long = System::currentTimeMillis,
    /** Public so callers report the same number this compared against, rather than a second one. */
    val currentVersion: String = CLI_VERSION,
    val currentSchema: Int = SCHEMA_VERSION,
) {

    /**
     * The newest release, from the cache when it is fresh and from the network otherwise.
     *
     * [force] is for `loopky update`, which is a direct question and must not answer it out of a
     * day-old file.
     */
    suspend fun latest(force: Boolean = false): ReleaseManifest? {
        val cached = readCache()
        if (!force && cached != null && now() - cached.checkedAt < TTL_MS) {
            return cached.manifest()
        }
        // A fetch that fails keeps the last answer and only moves the timestamp. A release that
        // was published stays published, so a transient failure must never leave the client
        // knowing *less* than it did a minute ago — and the timestamp still has to move, or an
        // offline box asks again on every invocation.
        val known = fetch() ?: cached?.manifest()
        writeCache(CacheRecord(checkedAt = now(), version = known?.version, schema = known?.schema))
        return known
    }

    /** [latest], reduced to the only thing most callers act on. */
    suspend fun check(force: Boolean = false): UpdateAvailable? = available(latest(force))

    /** Whether [manifest] is newer than this binary, and what to say about it. */
    fun available(manifest: ReleaseManifest?): UpdateAvailable? {
        if (manifest == null) return null
        if (!isNewer(manifest.version, currentVersion)) return null
        return UpdateAvailable(
            version = manifest.version,
            schema = manifest.schema,
            schemaChanged = manifest.schema != currentSchema,
        )
    }

    /** `https://github.com/<repo>/releases/download/v<version>/<asset>` — a pinned, not-latest URL. */
    fun assetUrl(version: String, asset: String): String =
        "https://github.com/$repo/releases/download/v$version/$asset"

    private suspend fun fetch(): ReleaseManifest? {
        val url = "https://github.com/$repo/releases/latest/download/$MANIFEST_ASSET"
        val response = runSuspendCatching {
            fetcher.send(HttpRequest(url = url, timeoutMs = TIMEOUT_MS)).getOrThrow()
        }.getOrElse {
            Log.d(TAG, "update check could not reach $url: ${it.message}")
            return null
        }
        if (!response.isSuccess) {
            // A release published before the manifest existed 404s here. Not a fault, and not
            // worth a word on stderr — it is indistinguishable from "no releases yet".
            Log.d(TAG, "update check got HTTP ${response.statusCode} from $url")
            return null
        }
        return runCatching { manifestJson.decodeFromString<ReleaseManifest>(response.body) }
            .getOrElse {
                Log.d(TAG, "update check could not read $MANIFEST_ASSET: ${it.message}")
                null
            }
    }

    private fun cacheFile(): Path = configHome.resolve(CACHE_FILE)

    private fun readCache(): CacheRecord? = runCatching {
        val file = cacheFile()
        if (!Files.exists(file)) return null
        manifestJson.decodeFromString<CacheRecord>(Files.readString(file))
    }.getOrElse {
        Log.d(TAG, "update-check cache is unreadable, treating it as absent: ${it.message}")
        null
    }

    /**
     * Best-effort, and silent when it fails: a read-only config directory is a reason to check
     * every time, never a reason to stop working. Written through a temp file for the same reason
     * [com.github.jvsena42.loopky.data.storage.JsonFileStore] is — a process killed mid-write
     * leaves the previous answer rather than a truncated file the next run has to discard.
     */
    private fun writeCache(record: CacheRecord) {
        runCatching {
            val file = cacheFile()
            ConfigHome.prepare(file.parent)
            val temp = Files.createTempFile(file.parent, CACHE_FILE, ".tmp")
            runCatching {
                Files.writeString(temp, manifestJson.encodeToString(record))
                Files.move(temp, file, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE)
            }.onFailure {
                Files.deleteIfExists(temp)
                throw it
            }
        }.onFailure { Log.d(TAG, "could not write the update-check cache: ${it.message}") }
    }

    @Serializable
    private data class CacheRecord(
        @SerialName("checked_at") val checkedAt: Long,
        val version: String? = null,
        val schema: Int? = null,
    ) {
        /** Null for a cached *failure* — the attempt is remembered, an answer was never had. */
        fun manifest(): ReleaseManifest? =
            if (version != null && schema != null) ReleaseManifest(version, schema) else null
    }

    companion object {
        const val DEFAULT_REPO = "jvsena42/loopky"

        /** The manifest asset, generated by `.github/workflows/release.yml` from the built binary. */
        const val MANIFEST_ASSET = "latest.json"

        private const val CACHE_FILE = "update-check.json"
        private const val TAG = "Loopky/UpdateCheck"
        private const val TTL_MS = 24L * 60 * 60 * 1000

        /**
         * Deliberately short. This runs concurrently with the command, so on the one invocation a
         * day that actually goes to the network it overlaps a homeserver round trip — but the
         * process still waits for it before printing, and a stalled check must not become a
         * stalled `deck list`.
         */
        private const val TIMEOUT_MS = 2_000L

        private val manifestJson = Json {
            ignoreUnknownKeys = true
            encodeDefaults = true
        }

        /**
         * Whether the ambient check should run at all.
         *
         * `update` is excluded because it asks the same question itself, unconditionally and
         * uncached — a notice above its own answer would be the same sentence twice.
         */
        fun enabled(args: Args, env: (String) -> String? = System::getenv): Boolean = when {
            args.has("no-update-check") -> false
            env("LOOPKY_NO_UPDATE_CHECK")?.isNotBlank() == true -> false
            args.verb == "update" -> false
            else -> true
        }

        /**
         * Whether [candidate] is a later release than [current].
         *
         * Numeric dotted parts only, and **false whenever either side does not parse** — a
         * comparison it cannot make must never resolve to "yes, update", which would send a
         * self-updater at a download on the strength of a string it did not understand. A
         * pre-release suffix (`0.9.0-rc1`) sorts before the plain version it precedes; `latest`
         * never points at one, so this only ever runs when the *installed* copy is the RC.
         */
        fun isNewer(candidate: String, current: String): Boolean {
            val left = parseVersion(candidate) ?: return false
            val right = parseVersion(current) ?: return false
            val size = maxOf(left.numbers.size, right.numbers.size)
            for (index in 0 until size) {
                val a = left.numbers.getOrElse(index) { 0 }
                val b = right.numbers.getOrElse(index) { 0 }
                if (a != b) return a > b
            }
            // Same numbers: a plain version is newer than the pre-release of itself, and nothing
            // else here is orderable — two different suffixes compare equal rather than guessed at.
            return !left.preRelease && right.preRelease
        }

        private data class ParsedVersion(val numbers: List<Int>, val preRelease: Boolean)

        private fun parseVersion(raw: String): ParsedVersion? {
            val trimmed = raw.trim().removePrefix("v")
            val core = trimmed.substringBefore('-').substringBefore('+')
            val numbers = core.split('.').map { it.toIntOrNull() ?: return null }
            return ParsedVersion(numbers, trimmed != core)
        }
    }
}

/**
 * Who to ask about updates, and how this copy was installed — resolved once per invocation, before
 * the command runs, because the check starts concurrently with it.
 */
data class Updates(val checker: UpdateChecker, val installation: Installation) {
    /** Pair what the check found with the installation, which is what decides the advice. */
    fun notice(available: UpdateAvailable?) = UpdateNotice(available, installation)
}

/** What the ambient check found, and the installation whose own upgrade command has to be quoted. */
data class UpdateNotice(val available: UpdateAvailable?, val installation: Installation)

/**
 * The one line a person is told about an update, on stderr, once.
 *
 * The instruction changes with the installation because a wrong one is worse than none: telling
 * somebody on a Homebrew build to run `loopky update` sends them at a command that will refuse,
 * and telling a container to self-update describes a change that vanishes with the container.
 */
fun updateNotice(update: UpdateAvailable, installation: Installation, repo: String = UpdateChecker.DEFAULT_REPO): String {
    // No "loopky" in the sentence: every line this goes on is already prefixed with `loopky: `,
    // and "loopky: loopky 0.9.0 is out" is what reads back when it is repeated here.
    val head = if (update.schemaChanged) {
        "version ${update.version} is out (you have $CLI_VERSION) and its --json schema is " +
            "${update.schema}, not $SCHEMA_VERSION — a parser written against $SCHEMA_VERSION may be wrong."
    } else {
        "version ${update.version} is out (you have $CLI_VERSION)."
    }
    return "$head ${updateAdvice(installation, update.version, repo)}"
}

/** What to run, given how this copy was installed. */
fun updateAdvice(installation: Installation, version: String, repo: String = UpdateChecker.DEFAULT_REPO): String =
    when (installation.method) {
        InstallMethod.Binary -> "Run `loopky update`."
        InstallMethod.Unknown ->
            "This binary's own path could not be determined, so `loopky update` cannot replace it — " +
                "re-run the installer: https://github.com/$repo/releases/latest"
        InstallMethod.Homebrew -> "Installed by Homebrew — run `brew upgrade loopky`."
        InstallMethod.Debian ->
            "Installed from the .deb — download loopky_${version}_amd64.deb from " +
                "https://github.com/$repo/releases/latest and `dpkg -i` it. There is no apt repository."
        InstallMethod.Container ->
            "Running in a container — pull the image instead: `docker pull ghcr.io/$repo:$version`."
        InstallMethod.Jar ->
            "This is the jar distribution, which is a directory rather than a file — re-download it " +
                "from https://github.com/$repo/releases/latest"
    }
